name: dio_stub
description: a starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/lucavenir/dio_stub

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.19.1
  dio: ^5.9.1

dev_dependencies:
  test: ^1.25.6
  very_good_analysis: ^10.1.0
